### ISSUE TITLE
Document Python dependencies

### ISSUE THREAD

**Issue by joanibal** [mdolab/pygeo#131]
# Description of feature
Figure out all the decencies used by this package and possibly remove the unnecessary ones.

Add the dependencies to the `setup.py` file. 
The dependencies necessary to run the code should be listed under `install_requires` and dependencies needed for testing should be listed under `extra_requires`.
See pyOptSparse for an example.
https://github.com/mdolab/pyoptsparse/blob/5f9e836c246dcb8fab62688b5fcc0e023c96c551/setup.py#L60-L70

**Comment by joanibal** [comment]
@ArshSaja Can you take care of this before the next maintenance meeting?

**Comment by ArshSaja** [comment]
Sure, I will finish this soon

**Comment by ArshSaja** [comment]
I checked the dependencies of every single file. I don't see any unwanted dependencies here except `unittest`. But I think it does not need to be added since it's the from the default python package ?

**Comment by nwu63** [comment]
I checked again and did not notice anything other than:
1. some minor fixes in #149 
2. the MPI issue detailed in #85 

Closing the issue.
