### ISSUE TITLE
Is there a way to link design variables of shared nodes in multi block FFDs?

### ISSUE THREAD

**Issue by arnalj** [mdolab/pygeo#205]
If an FFD box is composed of multiple blocks with shared nodes, `addLocalDV` will assign a degree of freedom to each of the shared nodes. Perturbations to the local design variables will thus "break" the connection of the previously shared nodes. It would be useful to assign a single degree of freedom to each of the shared nodes so that they move in unison. Is there a feature to preserve the connection of shared nodes across blocks?

I suppose that this could be achieved with `addShapeFunctionDV`, but I'm wondering if this can be achieved with `addLocalDV` directly.

**Comment by sseraj** [comment]
Have you tried this and run into issues? This should already be handled properly in DVGeometry by treating shared nodes as a single node.

**Comment by arnalj** [comment]
Yes, I have an FFD that is composed of 2 blocks that share a "face". Moving any of the shared nodes in one block does not affect the other block. I will post an example shortly if it's helpful.

Is there a method or flag that I have to invoke to treat shared nodes as a single node?

**Comment by sseraj** [comment]
This has worked for me before, but we could be using different setups. A MWE would be very helpful.

**Comment by arnalj** [comment]
So I made a MWE, and it works beautifully. Perhaps the issue is with my FFD, and the blocks are not actually coincident? Regardless, it seems that the issue is not with pyGeo.

**Comment by sseraj** [comment]
Yes, it could be an issue with the FFD. The tolerance for the [shared node check](https://github.com/mdolab/pygeo/blob/9e357a34b3261a7d60c7217e17e1dd1bf15cf19c/pygeo/geo_utils/remove_duplicates.py#L123) is 1e-4, so if the distance between FFD nodes is greater than that, they are not considered the same node.

**Comment by sseraj** [comment]
Closing as resolved
