### ISSUE TITLE
Issue with determining interior points

### ISSUE THREAD

**Issue by arnalj** [mdolab/pygeo#211]
## Description
I made a multi-block FFD box that completely encloses a geometry. However, when I add the point set (an .stl file), I get a warning that a number of points are not projected to the tolerance. I believe this warning is given when an FFD box does not fully enclose the geometry. However, that isn't the case here, the FFD box does in fact enclose the geometry.

Any suggestions on a work around would be very appreciated.

I've prepared a minimum working example with a simplified geometry:
[MWE.zip](https://github.com/mdolab/pygeo/files/12073934/MWE.zip)

### Steps to reproduce issue

1. `python MWE.py`
2. Open the paraview file to see the FFD box, initial geometry, and "clipped" geometry

### Current behavior
Points in the geometry are clipped even though the geometry is fully enclosed by the FFD box. In the image attached, the blue surface is the original geometry and the white surface is the "clipped" geometry.
![MWE_picture](https://github.com/mdolab/pygeo/assets/134004064/32c51699-96ca-4bf7-9555-b53877671dba)

### Expected behavior
The geometry should not be altered

### Code versions
Using the MDO Lab's [docker image](https://hub.docker.com/r/mdolab/public)

**Comment by arnalj** [comment]
I think the problem has to do with the structure of my FFD box. When I break up the blocks so that each block has 6 faces, the problem goes away. Previously, blocks had 6 or more faces. 

Can someone confirm that this is a requirement for FFDs? Is this requirement documented?

Here is the new FFD:
[MWE_ffd2.xyz.txt](https://github.com/mdolab/pygeo/files/12080950/MWE_ffd2.xyz.txt)

**Comment by hajdik** [comment]
The problem is likely due to the embedding volume not fully containing the points. For information on the embedding volume and how to visualize it, see the [note in these docs](https://mdolab-pygeo.readthedocs-hosted.com/en/latest/getting_started.html).
