### ISSUE TITLE
Regression test fails when pyspline built with new intel compilers

### ISSUE THREAD

**Issue by eirikurj** [mdolab/pygeo#255]
## Description
When the `pyspline` dependency is built using the new `ifx` compiler, one regression test fails, more specifically the `test_ffdGeneration.py:TestFFDGeneration.test_c172_fitted`.

This is part of the effort in https://github.com/mdolab/docker/pull/266.

### Current behavior
```
(mpi) /home/***/repos/pygeo/tests/reg_tests/test_ffdGeneration.py:TestFFDGeneration.test_c172_fitted  ... FAIL (00:00:0.05, 185 MB)
Traceback (most recent call last):
  File "/home/***/repos/pygeo/tests/reg_tests/test_ffdGeneration.py", line 75, in test_c172_fitted
    np.testing.assert_allclose(referenceFFD.FFD.coef, outputFFD.FFD.coef, rtol=1e-14)
  File "/home/***/.pyenv/versions/3.11.9/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/***/.pyenv/versions/3.11.9/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/***/.pyenv/versions/3.11.9/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-14, atol=0

Mismatched elements: 2 / 384 (0.521%)
Max absolute difference: 3.10862447e-15
Max relative difference: 3.39416628e-14
 x: array([[-7.200000e-02, -1.985[690](https://github.com/mdolab/docker/actions/runs/10562481225/job/29260543794#step:13:691)e-02, -6.269900e-02],
       [-7.200000e-02,  2.042722e-02, -6.269900e-02],
       [ 1.672000e+00, -2.596212e-02, -6.269900e-02],...
 y: array([[-7.200000e-02, -1.985690e-02, -6.269900e-02],
       [-7.200000e-02,  2.042722e-02, -6.269900e-02],
       [ 1.672000e+00, -2.596212e-02, -6.269900e-02],...
```
### Expected behavior
Test should pass.

### Steps to reproduce
1. Compile `pyspline` with the new `ifx/icx` compilers
2. In `repos/pygeo/tests/` run `testflo -v -s -n 1 reg_tests/test_ffdGeneration.py:TestFFDGeneration.test_c172_fitted`

### Notes and possible solutions
Initially suspected the fix in pyspline to be the culprit (see https://github.com/mdolab/pyspline/pull/75), but the following tests indicate that this is not the case.

* Using `ifx/icx` and using an older version of pyspline (pre Wolfe condition fix in https://github.com/mdolab/pyspline/pull/75) does not change the behavior. Tests fail.
* Using `ifort`, but keeping `icx`, and old pyspline (pre https://github.com/mdolab/pyspline/pull/75). Tests pass.
* Using `ifort` with current pyspline. Tests pass.

This suggests that this is a compiler effect. Using the current pyspline repo and changing only the compiler flags with `ifx` and adding `-fp-model precise`, the test passes.

Briefly traced the inconsistencies to the solution from the `solve_3by3` subroutine in pyspline. However, there is nothing of note there, except that this further suggests some optimization behavior. Solutions tend to differ by one or two digits. For example, the below solution differs in the last two digits of the second element, 
```
x = 0.455291047469981,  3.436295051154207E-002,  0.965361895804195 
x = 0.455291047469981,  3.436295051154215E-002,  0.965361895804195 
```

For a balance of performance and consistency, we could add the flag `-fp-model precise` (the default is `-fp-model fast=1`).
However, since we have not done any real profiling of the code, the performance impact of this flag is not clear.
With this approach we need to decide, do we want to the code to be as fast as possible (without being wrong) or do we want to fully comply with IEEE standards for arithmetic operations, and have consistent and reproducible results (on different systems).

Another option (to get tests to pass) is to relax the tolerance and accept that different compilers will generate slightly different behavior with the current compiler flags.

Let me know what you think, but if someone has the time to look into this further, that would be appreciated.

**Comment by A-CGray** [comment]
I vote we increase the tolerance, I think agreement to a relative error of 1e-13 is perfectly fine across different compilers

**Comment by eirikurj** [comment]
Does anyone else have other opinions @mdolab/pygeo_maintainers? If not, we can go ahead with #259.
