### ISSUE TITLE
Rename `addGeoDV` functions

### ISSUE THREAD

**Issue by nwu63** [mdolab/pygeo#33]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Refactor

## Description
I propose that we change some of the function names, which are unnecessarily verbose:
- `addGeoDVGlobal` -> `addGlobalDV`
- `addGeoDVLocal` -> `addLocalDV`
- `addGeoDVSectionLocal` -> `addSectionLocalDV`

**Comment by eirikurj** [comment]
I think that is probably fine. What about 
`addGeoDVSectionLocal -> addLocalSectionDV`

In the case we want to maintain backwards compatibility for some time we should create wrapper functions with deprecation warnings.

**Comment by nwu63** [comment]
I think we should open this up to the rest of the group to make sure these names are logical. Agreed on the deprecation warning, which I explained [here](https://github.com/mdolab/pytacs/issues/12#issuecomment-634911208)
