### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by nwu63** [mdolab/pygeo#44]
# Description
- [ ] Update tests to use testflo
- [ ] Add coverage report since this is pure Python

**Comment by bbrelje** [comment]
working on it

**Comment by anilyil** [comment]
@bbrelje most pygeo tests were already moved to testflo in here: https://github.com/mdolab/pygeo/tree/master/tests I think last time I checked, there was one failing test. We need to fix that, and possibly extend the test coverage a bit.
