### ISSUE TITLE
Extract airfoil data from a geometry model

### ISSUE THREAD

**Issue by GuardZ** [mdolab/pygeo#64]
Hi, I am sorry to bother your guys.

I am trying to generate a wing by using **pyGeo('liftingSurface',...)**. 
But the first thing I met is how to get the airfoil data from the existing geometry model.

So I am trying to ask for a suggestion that
Is there a way to extract airfoil data from several sections in an existing geometry model?

Again, sorry for this issue and many thanks.

**Comment by nwu63** [comment]
This is something for you to figure out, since that's not the usual workflow for us and is not related in any way to the functionality in pygeo.

**Comment by joanibal** [comment]
If the geometry is part of a structured mesh you could use adflow to print out slice files which contain geometry information.

Otherwise, I'm not sure

**Comment by GuardZ** [comment]
Thanks for all your replies. Here are my findings in these days:
By using the CAITA software,
    1.  CATIA - Shape - Digitized Shape Editor
        In this mode, 
        Discretize Curves - Parameter+Positions - Points=280 - Apply
        Export - Grouped - Apply

    2.  The data file will export data by X coordinates sequence
        In this way, it is a good choice to export the upper foil and lower foil separately.
