### ISSUE TITLE
DVConstraints test currently fails due to no numpy-stl installation

### ISSUE THREAD

**Issue by bbrelje** [mdolab/pygeo#66]
## Description
Numpy stl not found during Azure tests

### Steps to reproduce issue
Make a PR
The tests fail on DVConstraints because stl cannot be found

### Current behavior
…

### Expected behavior
pip install -e .[testing] installs the optional numpy-stl dependency

@nwu63 or someone, do you know why the Azure transition changed the way pygeo is installed on the machine during reg tests?

**Comment by nwu63** [comment]
Yeah, [this file](https://github.com/mdolab/pygeo/blob/master/.github/build_real.sh) is incorrect -- we should change it to `pip install .[testing]`.
