### ISSUE TITLE
Nondeterministic test failure

### ISSUE THREAD

**Issue by nwu63** [mdolab/pygeo#89]
## Description
Sometimes when you run the tests, `test_DVGeometry.py:RegTestPyGeo.test_21` will randomly fail. The nature of the failure is that some entries in the numpy array in the dictinoary `dIdx: mainAxis: x_axis` are swapped. It's unclear why or how, but maybe it has to do with the way we loop over dictionary keys or something.

### Steps to reproduce issue
Unfortunately not reliably reproducible :( but this happened on some of the CI runs of #88 and was observed previously by @eirikurj.

**Comment by nwu63** [comment]
I am able to now reproduce this failure reliably on my local machine, but the fact that buildbot passes means this is not reproducible on Docker.

**Comment by anilyil** [comment]
My ARM images replicated this issue 3 out of 3 times I tried, so I will look into this. Mentioned this in mdolab/docker#169

**Comment by nwu63** [comment]
This is most curious. I installed `numpy==1.19.2` locally and now the error's gone, but the error's there with `numpy=1.19.5`.

**Comment by anilyil** [comment]
I have `numpy==1.21.5` and `scipy==1.2.1` on my arm image and the pygeo test fails consistently. It's on my list to do.

**Comment by sseraj** [comment]
Can we skip this test until the issue is resolved? Pipelines are now failing regularly.

**Comment by anilyil** [comment]
I am working on a fix for this now. Will disable the test if I cannot figure it out.
